using Flenergy.Data.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;

namespace Flenergy.Data
{
    public static class DummyData
    {

        public static void SeedStatesData(this ModelBuilder builder)
        {
            builder.Entity<AdmStates>().HasData(
                new AdmStates[]
                {
                    new AdmStates {StateId = 1, StateName = "Abia"},
                    new AdmStates {StateId = 2, StateName = "Adamawa"},
                    new AdmStates {StateId = 3, StateName = "Akwa-Ibom"},
                    new AdmStates {StateId = 4, StateName = "Anambra"},
                    new AdmStates {StateId = 5, StateName = "Bauchi"},
                    new AdmStates {StateId = 6, StateName = "Bayelsa"},
                    new AdmStates {StateId = 7, StateName = "Benue"},
                    new AdmStates {StateId = 8, StateName = "Borno"},
                    new AdmStates {StateId = 9, StateName = "Cross River"},
                    new AdmStates {StateId = 10, StateName = "Delta"},
                    new AdmStates {StateId = 11, StateName = "Ebonyi"},
                    new AdmStates {StateId = 12, StateName = "Edo"},
                    new AdmStates {StateId = 13, StateName = "Ekiti"},
                    new AdmStates {StateId = 14, StateName = "Enugu"},
                    new AdmStates {StateId = 15, StateName = "FCT"},
                    new AdmStates {StateId = 16, StateName = "Gombe"},
                    new AdmStates {StateId = 17, StateName = "Imo"},
                    new AdmStates {StateId = 18, StateName = "Jigawa"},
                    new AdmStates {StateId = 19, StateName = "Kaduna"},
                    new AdmStates {StateId = 20, StateName = "Kano"},
                    new AdmStates {StateId = 21, StateName = "Katsina"},
                    new AdmStates {StateId = 22, StateName = "Kebbi"},
                    new AdmStates {StateId = 23, StateName = "Kogi"},
                    new AdmStates {StateId = 24, StateName = "Kwara"},
                    new AdmStates {StateId = 25, StateName = "Lagos"},
                    new AdmStates {StateId = 26, StateName = "Nassarawa"},
                    new AdmStates {StateId = 27, StateName = "Niger"},
                    new AdmStates {StateId = 28, StateName = "Ogun"},
                    new AdmStates {StateId = 29, StateName = "Ondo"},
                    new AdmStates {StateId = 30, StateName = "Osun"},
                    new AdmStates {StateId = 31, StateName = "Oyo"},
                    new AdmStates {StateId = 32, StateName = "Plateau"},
                    new AdmStates {StateId = 33, StateName = "Rivers"},
                    new AdmStates {StateId = 34, StateName = "Sokoto"},
                    new AdmStates {StateId = 35, StateName = "Taraba"},
                    new AdmStates {StateId = 36, StateName = "Yobe"},
                    new AdmStates {StateId = 37, StateName = "Zamfara"},

                }
                );
        }

        public static void SeedLgaData(this ModelBuilder builder)
        {
            builder.Entity<LocalGovernment>().HasData(
                new LocalGovernment[]
                {
                    //Abia
                    new LocalGovernment {  LocalGovernmentId = 1, LocalGovernmentName = "Aba North", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 2, LocalGovernmentName = "Aba South", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 3, LocalGovernmentName = "Arochukwu", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 4, LocalGovernmentName = "Bende", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 5, LocalGovernmentName = "Ikwuano", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 6, LocalGovernmentName = "Isiala Ngwa North", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 7, LocalGovernmentName = "Isiala Ngwa South", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 8, LocalGovernmentName = "Isuikwuato", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 9, LocalGovernmentName = "Obi Ngwa", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 10, LocalGovernmentName = "Ohafia", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 11, LocalGovernmentName = "Osisioma", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 12, LocalGovernmentName = "Ugwunagbo", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 13, LocalGovernmentName = "Ukwa East", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 14, LocalGovernmentName = "Ukwa West", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 15, LocalGovernmentName = "Umuahia North", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 16, LocalGovernmentName = "Umuahia South", StateId = 1 },
                    new LocalGovernment {  LocalGovernmentId = 17, LocalGovernmentName = "Umu Nneochi", StateId = 1 },

                    //Adamawa
                    new LocalGovernment {  LocalGovernmentId = 18, LocalGovernmentName = "Demsa", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 19, LocalGovernmentName = "Fufure", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 20, LocalGovernmentName = "Ganye", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 21, LocalGovernmentName = "Gayuk", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 22, LocalGovernmentName = "Gombi", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 23, LocalGovernmentName = "Grie", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 24, LocalGovernmentName = "Hong", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 25, LocalGovernmentName = "Jada", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 26, LocalGovernmentName = "Larmurde", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 27, LocalGovernmentName = "Madagali", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 28, LocalGovernmentName = "Maiha", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 29, LocalGovernmentName = "Mayo Belwa", StateId = 2},
                    new LocalGovernment {  LocalGovernmentId = 30, LocalGovernmentName = "Michika", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 31, LocalGovernmentName = "Mubi North", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 32, LocalGovernmentName = "Mubi South", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 33, LocalGovernmentName = "Numan", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 34, LocalGovernmentName = "Shelleng", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 35, LocalGovernmentName = "Song", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 36, LocalGovernmentName = "Toungo", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 37, LocalGovernmentName = "Yola North", StateId = 2 },
                    new LocalGovernment {  LocalGovernmentId = 38, LocalGovernmentName = "Yola South", StateId = 2 },

                    //AkwaIbom

                    new LocalGovernment {  LocalGovernmentId = 39, LocalGovernmentName = "Abak", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 40, LocalGovernmentName = "Eastern Obolo", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 41, LocalGovernmentName = "Eket", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 42, LocalGovernmentName = "Esit Eket", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 43, LocalGovernmentName = "Essien Udim", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 44, LocalGovernmentName = "Etim Ekpo", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 45, LocalGovernmentName = "Etinan", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 46, LocalGovernmentName = "Ibeno", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 47, LocalGovernmentName = "Ibesikpo Asutan", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 48, LocalGovernmentName = "Ibiono-Ibom", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 49, LocalGovernmentName = "Ika", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 50, LocalGovernmentName = "Ikono", StateId = 3},
                    new LocalGovernment {  LocalGovernmentId = 51, LocalGovernmentName = "Ikot Abasi", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 52, LocalGovernmentName = "Ikot Ekpene", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 53, LocalGovernmentName = "Ini", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 54, LocalGovernmentName = "Itu", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 55, LocalGovernmentName = "Mbo", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 56, LocalGovernmentName = "Mkpat-Enin", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 57, LocalGovernmentName = "Nsit-Atai", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 58, LocalGovernmentName = "Nsit-Ibom", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 59, LocalGovernmentName = "Nsit-Ubium", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 60, LocalGovernmentName = "Obot Akara", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 61, LocalGovernmentName = "Okobo", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 62, LocalGovernmentName = "Onna", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 63, LocalGovernmentName = "Oron", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 64, LocalGovernmentName = "Oruk Anam", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 65, LocalGovernmentName = "Udung-Uko", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 66, LocalGovernmentName = "Ukanafun", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 67, LocalGovernmentName = "Uruan", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 68, LocalGovernmentName = "Urue-Offong Oruko", StateId = 3 },
                    new LocalGovernment {  LocalGovernmentId = 69, LocalGovernmentName = "Uyo", StateId = 3 },


                    //Anambra
                    new LocalGovernment {  LocalGovernmentId = 70, LocalGovernmentName = "Aguata", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 71, LocalGovernmentName = "Anambra East", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 72, LocalGovernmentName = "Anambra West", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 73, LocalGovernmentName = "Anaocha", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 74, LocalGovernmentName = "Awka North", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 75, LocalGovernmentName = "Awka South", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 76, LocalGovernmentName = "Ayamelum", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 77, LocalGovernmentName = "Dunukofia", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 78, LocalGovernmentName = "Ekwusigo", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 79, LocalGovernmentName = "Idemili North", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 80, LocalGovernmentName = "Idemili South", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 81, LocalGovernmentName = "Ihiala", StateId = 4},
                    new LocalGovernment {  LocalGovernmentId = 82, LocalGovernmentName = "Njikoka", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 83, LocalGovernmentName = "Nnewi North", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 84, LocalGovernmentName = "Nnewi South", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 85, LocalGovernmentName = "Ogbaru", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 86, LocalGovernmentName = "Onitsha North", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 87, LocalGovernmentName = "Onitsha South", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 88, LocalGovernmentName = "Orumba North", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 89, LocalGovernmentName = "Orumba South", StateId = 4 },
                    new LocalGovernment {  LocalGovernmentId = 90, LocalGovernmentName = "Oyi", StateId = 4 },

                    //Bauchi

                    new LocalGovernment {  LocalGovernmentId = 91, LocalGovernmentName = "Alkaleri", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 92, LocalGovernmentName = "Bauchi", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 93, LocalGovernmentName = "Bogoro", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 94, LocalGovernmentName = "Damban", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 95, LocalGovernmentName = "Darazo", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 96, LocalGovernmentName = "Dass", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 97, LocalGovernmentName = "Gamawa", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 98, LocalGovernmentName = "Ganjuwa", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 99, LocalGovernmentName = "Giade", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 100, LocalGovernmentName = "Itas-Gadau", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 101, LocalGovernmentName = "Jama are", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 102, LocalGovernmentName = "Katagum", StateId = 5},
                    new LocalGovernment {  LocalGovernmentId = 103, LocalGovernmentName = "Kirfi", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 104, LocalGovernmentName = "Misau", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 105, LocalGovernmentName = "Ningi", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 106, LocalGovernmentName = "Shira", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 107, LocalGovernmentName = "Tafawa Balewa", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 108, LocalGovernmentName = "Toro", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 109, LocalGovernmentName = "Warji", StateId = 5 },
                    new LocalGovernment {  LocalGovernmentId = 110, LocalGovernmentName = "Zaki", StateId = 5 },


                    //Bayelsa

                    new LocalGovernment {  LocalGovernmentId = 111, LocalGovernmentName = "Brass", StateId = 6 },
                    new LocalGovernment {  LocalGovernmentId =112, LocalGovernmentName = "Ekeremor", StateId = 6 },
                    new LocalGovernment {  LocalGovernmentId =113, LocalGovernmentName = "Kolokuma Opokuma", StateId = 6 },
                    new LocalGovernment {  LocalGovernmentId =114, LocalGovernmentName = "Nembe", StateId = 6 },
                    new LocalGovernment {  LocalGovernmentId = 115, LocalGovernmentName = "Ogbia", StateId = 6 },
                    new LocalGovernment {  LocalGovernmentId = 116, LocalGovernmentName = "Sagbama", StateId = 6 },
                    new LocalGovernment {  LocalGovernmentId = 117, LocalGovernmentName = "Southern Ijaw", StateId = 6 },
                    new LocalGovernment {  LocalGovernmentId =118, LocalGovernmentName = "Yenagoa", StateId = 6 },




                    //Benue
                    new LocalGovernment {  LocalGovernmentId = 119, LocalGovernmentName = "Agatu", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 120, LocalGovernmentName = "Apa", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 121, LocalGovernmentName = "Ado", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 122, LocalGovernmentName = "Buruku", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 123, LocalGovernmentName = "Gboko", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 124, LocalGovernmentName = "Guma", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 125, LocalGovernmentName = "Gwer East", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 126, LocalGovernmentName = "Gwer West", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 127, LocalGovernmentName = "Katsina-Ala", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 128, LocalGovernmentName = "Konshisha", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 129, LocalGovernmentName = "Kwande", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 130, LocalGovernmentName = "Logo", StateId = 7},
                    new LocalGovernment {  LocalGovernmentId = 131, LocalGovernmentName = "Makurdi", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 132, LocalGovernmentName = "Obi", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 133, LocalGovernmentName = "Ogbadibo", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 134, LocalGovernmentName = "Ohimini", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 135, LocalGovernmentName = "Oju", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 136, LocalGovernmentName = "Okpokwu", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 137, LocalGovernmentName = "Oturkpo", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 138, LocalGovernmentName = "Tarka", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 139, LocalGovernmentName = "Ukum", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 140, LocalGovernmentName = "Ushongo", StateId = 7 },
                    new LocalGovernment {  LocalGovernmentId = 141, LocalGovernmentName = "Vandeikya", StateId = 7 },

                    //Borno

                    new LocalGovernment {  LocalGovernmentId = 142, LocalGovernmentName = "Abadam", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 143, LocalGovernmentName = "Askira-Uba", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 144, LocalGovernmentName = "Bama", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 145, LocalGovernmentName = "Bayo", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 146, LocalGovernmentName = "Biu", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 147, LocalGovernmentName = "Chibok", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 148, LocalGovernmentName = "Damboa", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 149, LocalGovernmentName = "Dikwa", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 150, LocalGovernmentName = "Gubio", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 151, LocalGovernmentName = "Guzamala", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 152, LocalGovernmentName = "Gwoza", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 153, LocalGovernmentName = "Hawul", StateId = 8},
                    new LocalGovernment {  LocalGovernmentId = 154, LocalGovernmentName = "Jere", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 155, LocalGovernmentName = "Kaga", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 156, LocalGovernmentName = "Kala-Balge", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 157, LocalGovernmentName = "Konduga", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 158, LocalGovernmentName = "Kukawa", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 159, LocalGovernmentName = "Kwaya Kusar", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 160, LocalGovernmentName = "Mafa", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 161, LocalGovernmentName = "Magumeri", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 162, LocalGovernmentName = "Maiduguri", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 163, LocalGovernmentName = "Marte", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 164, LocalGovernmentName = "Mobbar", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 165, LocalGovernmentName = "Monguno", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 166, LocalGovernmentName = "Ngala", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 167, LocalGovernmentName = "Nganzai", StateId = 8 },
                    new LocalGovernment {  LocalGovernmentId = 168, LocalGovernmentName = "Shani", StateId = 8 },

                    //Cross River
                    new LocalGovernment {  LocalGovernmentId = 169, LocalGovernmentName = "Abi", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 170, LocalGovernmentName = "Akamkpa", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 171, LocalGovernmentName = "Akpabuyo", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 172, LocalGovernmentName = "Bakassi", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 173, LocalGovernmentName = "Bekwarra", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 174, LocalGovernmentName = "Biase", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 175, LocalGovernmentName = "Boki", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 176, LocalGovernmentName = "Calabar Municipal", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 177, LocalGovernmentName = "Calabar South", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 178, LocalGovernmentName = "Etung", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 179, LocalGovernmentName = "Ikom", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 180, LocalGovernmentName = "Obanliku", StateId = 9},
                    new LocalGovernment {  LocalGovernmentId = 181, LocalGovernmentName = "Obubra", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 182, LocalGovernmentName = "Obudu", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 183, LocalGovernmentName = "Odukpani", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 184, LocalGovernmentName = "Ogoja", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 185, LocalGovernmentName = "Yakuur", StateId = 9 },
                    new LocalGovernment {  LocalGovernmentId = 186, LocalGovernmentName = "Yala", StateId = 9 },


                    //Delta
                    new LocalGovernment {  LocalGovernmentId = 187, LocalGovernmentName = "Aniocha North", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 188, LocalGovernmentName = "Aniocha South", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 189, LocalGovernmentName = "Bomadi", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 190, LocalGovernmentName = "Burutu", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 191, LocalGovernmentName = "Ethiope East", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 192, LocalGovernmentName = "Ethiope West", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 193, LocalGovernmentName = "Ika North East", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 194, LocalGovernmentName = "Ika South", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 195, LocalGovernmentName = "Isoko North", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 196, LocalGovernmentName = "Isoko South", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 197, LocalGovernmentName = "Ndokwa East", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 198, LocalGovernmentName = "Ndokwa West", StateId = 10},
                    new LocalGovernment {  LocalGovernmentId = 199, LocalGovernmentName = "Okpe", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 200, LocalGovernmentName = "Oshimili North", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 201, LocalGovernmentName = "Oshimili South", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 202, LocalGovernmentName = "Patani", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 203, LocalGovernmentName = "Sapele", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 204, LocalGovernmentName = "Udu", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 205, LocalGovernmentName = "Ughelli North", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 206, LocalGovernmentName = "Ughelli South", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 207, LocalGovernmentName = "Ukwuani", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 208, LocalGovernmentName = "Uvwie", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 209, LocalGovernmentName = "Warri North", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 210, LocalGovernmentName = "Warri South", StateId = 10 },
                    new LocalGovernment {  LocalGovernmentId = 211, LocalGovernmentName = "Warri South West", StateId = 10 },

                    //Ebonyi
                    new LocalGovernment {  LocalGovernmentId = 212, LocalGovernmentName = "Abakaliki", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 213, LocalGovernmentName = "Afikpo North", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 214, LocalGovernmentName = "Afikpo South", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 215, LocalGovernmentName = "Ebonyi", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 216, LocalGovernmentName = "Ezza North", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 217, LocalGovernmentName = "Ezza South", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 218, LocalGovernmentName = "Ikwo", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 219, LocalGovernmentName = "Ishielu", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 220, LocalGovernmentName = "Calabar South", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 221, LocalGovernmentName = "Ivo", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 222, LocalGovernmentName = "Izzi", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 223, LocalGovernmentName = "Ohaozara", StateId = 11},
                    new LocalGovernment {  LocalGovernmentId = 224, LocalGovernmentName = "Ohaukwu", StateId = 11 },
                    new LocalGovernment {  LocalGovernmentId = 225, LocalGovernmentName = "Onicha", StateId = 11 },


                    //Edo
                    new LocalGovernment {  LocalGovernmentId = 226, LocalGovernmentName = "Akoko-Edo", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 227, LocalGovernmentName = "Egor", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 228, LocalGovernmentName = "Esan Central", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 229, LocalGovernmentName = "Esan North-East", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 230, LocalGovernmentName = "Esan South-East", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 231, LocalGovernmentName = "Esan West", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 232, LocalGovernmentName = "Etsako Central", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 233, LocalGovernmentName = "Etsako East", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 234, LocalGovernmentName = "Etsako West", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 235, LocalGovernmentName = "Igueben", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 236, LocalGovernmentName = "Ikpoba Okha", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 237, LocalGovernmentName = "Orhionmwon", StateId = 12},
                    new LocalGovernment {  LocalGovernmentId = 238, LocalGovernmentName = "Oredo", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 239, LocalGovernmentName = "Ovia North-East", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 240, LocalGovernmentName = "Ovia South-West", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 241, LocalGovernmentName = "Owan East", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 242, LocalGovernmentName = "Owan East", StateId = 12 },
                    new LocalGovernment {  LocalGovernmentId = 243, LocalGovernmentName = "Uhunmwonde", StateId = 12 },


                    //Ekiti
                    new LocalGovernment {  LocalGovernmentId = 244, LocalGovernmentName = "Ado Ekiti", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 245, LocalGovernmentName = "Efon", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 246, LocalGovernmentName = "Ekiti East", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 247, LocalGovernmentName = "Ekiti South-West", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 248, LocalGovernmentName = "Esan South-East", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 249, LocalGovernmentName = "Ekiti West", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 250, LocalGovernmentName = "Emure", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 251, LocalGovernmentName = "Gbonyin", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 252, LocalGovernmentName = "Ido Osi", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 253, LocalGovernmentName = "Ijero", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 254, LocalGovernmentName = "Ikere", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 255, LocalGovernmentName = "Ikole", StateId = 13},
                    new LocalGovernment {  LocalGovernmentId = 256, LocalGovernmentName = "Ilejemeje", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 257, LocalGovernmentName = "Irepodun-Ifelodun", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 258, LocalGovernmentName = "Ise-Orun", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 259, LocalGovernmentName = "Moba", StateId = 13 },
                    new LocalGovernment {  LocalGovernmentId = 260, LocalGovernmentName = "Oye", StateId = 13 },


                    //Enugu

                    new LocalGovernment {  LocalGovernmentId = 261, LocalGovernmentName = "Aninri", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 262, LocalGovernmentName = "Awgu", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 263, LocalGovernmentName = "Enugu East", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 264, LocalGovernmentName = "Enugu North", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 265, LocalGovernmentName = "Enugu South", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 266, LocalGovernmentName = "Ezeagu", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 267, LocalGovernmentName = "Igbo Etiti", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 268, LocalGovernmentName = "Igbo Eze North", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 269, LocalGovernmentName = "Igbo Eze South", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 270, LocalGovernmentName = "Isi Uzo", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 271, LocalGovernmentName = "Nkanu East", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 272, LocalGovernmentName = "Nkanu West", StateId = 14},
                    new LocalGovernment {  LocalGovernmentId = 273, LocalGovernmentName = "Nsukka", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 274, LocalGovernmentName = "Oji River", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 275, LocalGovernmentName = "Udenu", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 276, LocalGovernmentName = "Udi", StateId = 14 },
                    new LocalGovernment {  LocalGovernmentId = 277, LocalGovernmentName = "Uzo Uwani", StateId = 14 },
                
                    //F.C.T
                    new LocalGovernment {  LocalGovernmentId = 278, LocalGovernmentName = "Abaji", StateId = 15 },
                    new LocalGovernment {  LocalGovernmentId = 279, LocalGovernmentName = "Bwari", StateId = 15 },
                    new LocalGovernment {  LocalGovernmentId = 280, LocalGovernmentName = "Gwagwalada", StateId = 15 },
                    new LocalGovernment {  LocalGovernmentId = 281, LocalGovernmentName = "Kuje", StateId = 15 },
                    new LocalGovernment {  LocalGovernmentId = 282, LocalGovernmentName = "Kwali", StateId = 15 },
                    new LocalGovernment {  LocalGovernmentId = 283, LocalGovernmentName = "Municipal Area Council", StateId = 15 },

                    //Gombe

                    new LocalGovernment {  LocalGovernmentId = 284, LocalGovernmentName = "Akko", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 285, LocalGovernmentName = "Balanga", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 286, LocalGovernmentName = "Billiri", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 287, LocalGovernmentName = "Dukku", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 288, LocalGovernmentName = "Funakaye", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 289, LocalGovernmentName = "Gombe", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 290, LocalGovernmentName = "Kaltungo", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 291, LocalGovernmentName = "Kwami", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 292, LocalGovernmentName = "Nafada", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 293, LocalGovernmentName = "Shongom", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 294, LocalGovernmentName = "Yamaltu", StateId = 16 },
                    new LocalGovernment {  LocalGovernmentId = 295, LocalGovernmentName = "Deba", StateId = 16},

                    //Imo
                    new LocalGovernment {  LocalGovernmentId = 296, LocalGovernmentName = "Aboh Mbaise", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 297, LocalGovernmentName = "Ahiazu Mbaise", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 298, LocalGovernmentName = "Ehime Mbano", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 299, LocalGovernmentName = "Ezinihitte", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 300, LocalGovernmentName = "Ideato North", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 301, LocalGovernmentName = "Ideato South", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 302, LocalGovernmentName = "Ihitte-Uboma", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 303, LocalGovernmentName = "Ikeduru", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 304, LocalGovernmentName = "Isiala Mbano", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 305, LocalGovernmentName = "Isu", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 306, LocalGovernmentName = "Mbaitoli", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 307, LocalGovernmentName = "Ngor Okpala", StateId = 17},
                    new LocalGovernment {  LocalGovernmentId = 308, LocalGovernmentName = "Njaba", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 309, LocalGovernmentName = "Nkwerre", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 310, LocalGovernmentName = "Nwangele", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 311, LocalGovernmentName = "Obowo", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 312, LocalGovernmentName = "Oguta", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 313, LocalGovernmentName = "Ohaji-Egbema", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 314, LocalGovernmentName = "Okigwe", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 315, LocalGovernmentName = "Orlu", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 316, LocalGovernmentName = "Orsu", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 317, LocalGovernmentName = "Oru East", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 318, LocalGovernmentName = "Oru West", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 319, LocalGovernmentName = "Owerri Municipal", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 320, LocalGovernmentName = "Owerri North", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 321, LocalGovernmentName = "Owerri West", StateId = 17 },
                    new LocalGovernment {  LocalGovernmentId = 322, LocalGovernmentName = "Unuimo", StateId = 17 },




                    //Jigawa

                    new LocalGovernment {  LocalGovernmentId = 323, LocalGovernmentName = "Auyo", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 324, LocalGovernmentName = "Babura", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 325, LocalGovernmentName = "Biriniwa", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 326, LocalGovernmentName = "Birnin Kudu", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 327, LocalGovernmentName = "Buji", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 328, LocalGovernmentName = "Dutse", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 329, LocalGovernmentName = "Gagarawa", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 330, LocalGovernmentName = "Garki", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 331, LocalGovernmentName = "Gumel", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 332, LocalGovernmentName = "Guri", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 333, LocalGovernmentName = "Gwaram", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 334, LocalGovernmentName = "Gwiwa", StateId = 18},
                    new LocalGovernment {  LocalGovernmentId = 335, LocalGovernmentName = "Hadejia", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 336, LocalGovernmentName = "Jahun", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 337, LocalGovernmentName = "Kafin Hausa", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 338, LocalGovernmentName = "Kazaure", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 339, LocalGovernmentName = "Kiri Kasama", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 340, LocalGovernmentName = "Kiyawa", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 341, LocalGovernmentName = "Kaugama", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 342, LocalGovernmentName = "Maigatari", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 343, LocalGovernmentName = "Malam Madori", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 344, LocalGovernmentName = "Miga", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 345, LocalGovernmentName = "Ringim", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 346, LocalGovernmentName = "Roni", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 347, LocalGovernmentName = "Sule Tankarkar", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 348, LocalGovernmentName = "Taura", StateId = 18 },
                    new LocalGovernment {  LocalGovernmentId = 349, LocalGovernmentName = "Yankwashi", StateId = 18 },

                    //Kaduna
                    new LocalGovernment {  LocalGovernmentId = 350, LocalGovernmentName = "Birnin Gwari", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 351, LocalGovernmentName = "Chikun", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 352, LocalGovernmentName = "Giwa", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 353, LocalGovernmentName = "Igabi", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 354, LocalGovernmentName = "Ikara", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 355, LocalGovernmentName = "Jaba", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 356, LocalGovernmentName = "Jema a", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 357, LocalGovernmentName = "Kachia", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 358, LocalGovernmentName = "Kaduna North", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 359, LocalGovernmentName = "Kaduna South", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 360, LocalGovernmentName = "Kagarko", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 361, LocalGovernmentName = "Kajuru", StateId = 19},
                    new LocalGovernment {  LocalGovernmentId = 362, LocalGovernmentName = "Kaura", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 363, LocalGovernmentName = "Kauru", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 364, LocalGovernmentName = "Kubau", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 365, LocalGovernmentName = "Kudan", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 366, LocalGovernmentName = "Lere", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 367, LocalGovernmentName = "Makarfi", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 368, LocalGovernmentName = "Sabon Gari", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 369, LocalGovernmentName = "Sanga", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 370, LocalGovernmentName = "Soba", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 371, LocalGovernmentName = "Zangon Kataf", StateId = 19 },
                    new LocalGovernment {  LocalGovernmentId = 372, LocalGovernmentName = "Zaria", StateId = 19 },


                    //Kano
                    new LocalGovernment {  LocalGovernmentId = 373, LocalGovernmentName = "Ajingi", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 374, LocalGovernmentName = "Albasu", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 375, LocalGovernmentName = "Bagwai", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 376, LocalGovernmentName = "Bebeji", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 377, LocalGovernmentName = "Bichi", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 378, LocalGovernmentName = "Bunkure", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 379, LocalGovernmentName = "Dala", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 380, LocalGovernmentName = "Dambatta", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 381, LocalGovernmentName = "Dawakin Kudu", StateId= 20 },
                    new LocalGovernment {  LocalGovernmentId = 382, LocalGovernmentName = "Dawakin Tofa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 383, LocalGovernmentName = "Doguwa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 384, LocalGovernmentName = "Fagge", StateId = 20},
                    new LocalGovernment {  LocalGovernmentId = 385, LocalGovernmentName = "Gabasawa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 386, LocalGovernmentName = "Garko", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 387, LocalGovernmentName = "Garun Mallam", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 388, LocalGovernmentName = "Gaya", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 389, LocalGovernmentName = "Gezawa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 390, LocalGovernmentName = "Gwale", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 391, LocalGovernmentName = "Gwarzo", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 392, LocalGovernmentName = "Kabo", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 393, LocalGovernmentName = "Kano Municipal", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 394, LocalGovernmentName = "Karaye", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 395, LocalGovernmentName = "Kibiya", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 396, LocalGovernmentName = "Kiru", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 397, LocalGovernmentName = "Kumbotso", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 398, LocalGovernmentName = "Kunchi", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 399, LocalGovernmentName = "Kura", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 400, LocalGovernmentName = "Madobi", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 401, LocalGovernmentName = "Makoda", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 402, LocalGovernmentName = "Minjibir", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 403, LocalGovernmentName = "Nasarawa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 404, LocalGovernmentName = "Rano", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 405, LocalGovernmentName = "Rimin Gado", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 406, LocalGovernmentName = "Rogo", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 407, LocalGovernmentName = "Shanono", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 408, LocalGovernmentName = "Sumaila", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 409, LocalGovernmentName = "Takai", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 410, LocalGovernmentName = "Tarauni", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 411, LocalGovernmentName = "Tofa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 412, LocalGovernmentName = "Tsanyawa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 413, LocalGovernmentName = "Tudun Wada", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 414, LocalGovernmentName = "Ungogo", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 415, LocalGovernmentName = "Warawa", StateId = 20 },
                    new LocalGovernment {  LocalGovernmentId = 416, LocalGovernmentName = "Wudil", StateId = 20 },



                    //Katsina
                    new LocalGovernment {  LocalGovernmentId = 417, LocalGovernmentName = "Bakori", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 418, LocalGovernmentName = "Batagarawa", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 419, LocalGovernmentName = "Batsari", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 420, LocalGovernmentName = "Baure", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 421, LocalGovernmentName = "Bindawa", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 422, LocalGovernmentName = "Charanchi", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 423, LocalGovernmentName = "Dandume", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 424, LocalGovernmentName = "Danja", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 425, LocalGovernmentName = "Dan Musa", StateId= 21 },
                    new LocalGovernment {  LocalGovernmentId = 426, LocalGovernmentName = "Daura", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 427, LocalGovernmentName = "Dutsi", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 428, LocalGovernmentName = "Dutsin Ma", StateId = 21},
                    new LocalGovernment {  LocalGovernmentId = 429, LocalGovernmentName = "Faskari", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 430, LocalGovernmentName = "Funtua", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 431, LocalGovernmentName = "Ingawa", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 432, LocalGovernmentName = "Jibia", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 433, LocalGovernmentName = "Kafur", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 434, LocalGovernmentName = "Kaita", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 435, LocalGovernmentName = "Kankara", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 436, LocalGovernmentName = "Kankia", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 437, LocalGovernmentName = "Katsina", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 438, LocalGovernmentName = "Kurfi", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 439, LocalGovernmentName = "Kusada", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 440, LocalGovernmentName = "Mai Adua", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 441, LocalGovernmentName = "Malumfashi", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 442, LocalGovernmentName = "Mani", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 443, LocalGovernmentName = "Mashi", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 444, LocalGovernmentName = "Matazu", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 445, LocalGovernmentName = "Musawa", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 446, LocalGovernmentName = "Rimi", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 447, LocalGovernmentName = "Sabuwa", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 448, LocalGovernmentName = "Safana", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 449, LocalGovernmentName = "Sandamu", StateId = 21 },
                    new LocalGovernment {  LocalGovernmentId = 450, LocalGovernmentName = "Zango", StateId = 21 },

                    //Kebbi

                    new LocalGovernment {  LocalGovernmentId = 451, LocalGovernmentName = "Aleiro", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 452, LocalGovernmentName = "Arewa Dandi", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 453, LocalGovernmentName = "Argungu", StateId = 22},
                    new LocalGovernment {  LocalGovernmentId = 454, LocalGovernmentName = "Augie", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 455, LocalGovernmentName = "Bagudo", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 456, LocalGovernmentName = "Birnin Kebbi", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 457, LocalGovernmentName = "Bunza", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 458, LocalGovernmentName = "Dandi", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 459, LocalGovernmentName = "Fakai", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 460, LocalGovernmentName = "Gwandu", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 461, LocalGovernmentName = "Jega", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 462, LocalGovernmentName = "Kalgo", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 463, LocalGovernmentName = "Koko Besse", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 464, LocalGovernmentName = "Maiyama", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 465, LocalGovernmentName = "Ngaski", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 466, LocalGovernmentName = "Sakaba", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 467, LocalGovernmentName = "Shanga", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 468, LocalGovernmentName = "Suru", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 469, LocalGovernmentName = "Wasagu Danko", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 470, LocalGovernmentName = "Yauri", StateId = 22 },
                    new LocalGovernment {  LocalGovernmentId = 471, LocalGovernmentName = "Zuru", StateId = 22 },


                    //kogi

                    new LocalGovernment {  LocalGovernmentId = 472, LocalGovernmentName = "Adavi", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 473, LocalGovernmentName = "Ajaokuta", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 474, LocalGovernmentName = "Ankpa", StateId = 23},
                    new LocalGovernment {  LocalGovernmentId = 475, LocalGovernmentName = "Bassa", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 476, LocalGovernmentName = "Dekina", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 477, LocalGovernmentName = "Ibaji", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 478, LocalGovernmentName = "Idah", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 479, LocalGovernmentName = "Igalamela Odolu", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 480, LocalGovernmentName = "Ijumu", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 481, LocalGovernmentName = "Kabba Bunu", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 482, LocalGovernmentName = "Kogi", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 483, LocalGovernmentName = "Lokoja", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 484, LocalGovernmentName = "Mopa Muro", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 485, LocalGovernmentName = "Ofu", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 486, LocalGovernmentName = "Ogori Magongo", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 487, LocalGovernmentName = "Okehi", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 488, LocalGovernmentName = "Okene", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 489, LocalGovernmentName = "Olamaboro", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 490, LocalGovernmentName = "Omala", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 491, LocalGovernmentName = "Yagba East", StateId = 23 },
                    new LocalGovernment {  LocalGovernmentId = 492, LocalGovernmentName = "Yagba West", StateId = 23 },


                    //Kwara
                    new LocalGovernment {  LocalGovernmentId = 493, LocalGovernmentName = "Asa", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 494, LocalGovernmentName = "Baruten", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 495, LocalGovernmentName = "Edu", StateId = 24},
                    new LocalGovernment {  LocalGovernmentId = 496, LocalGovernmentName = "Ekiti", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 497, LocalGovernmentName = "Ifelodun", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 498, LocalGovernmentName = "Ilorin East", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 499, LocalGovernmentName = "Ilorin West", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 500, LocalGovernmentName = "Ilorin South", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 501, LocalGovernmentName = "Irepodun", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 502, LocalGovernmentName = "Isin", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 503, LocalGovernmentName = "Kaiama", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 504, LocalGovernmentName = "Moro", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 505, LocalGovernmentName = "Offa", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 506, LocalGovernmentName = "Oke Ero", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 507, LocalGovernmentName = "Oyun", StateId = 24 },
                    new LocalGovernment {  LocalGovernmentId = 508, LocalGovernmentName = "Pategi", StateId = 24 },

                    //Lagos
                    new LocalGovernment {  LocalGovernmentId = 509, LocalGovernmentName = "Agege", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 510, LocalGovernmentName = "Ajeromi-Ifelodun", StateId = 25},
                    new LocalGovernment {  LocalGovernmentId = 511, LocalGovernmentName = "Alimosho", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 512, LocalGovernmentName = "Amuwo-Odofin", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 513, LocalGovernmentName = "Badagry", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 514, LocalGovernmentName = "Epe", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 515, LocalGovernmentName = "Eti Osa", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 516, LocalGovernmentName = "Ibeju-Lekki", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 517, LocalGovernmentName = "Ifako-Ijaiye", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 518, LocalGovernmentName = "Ikeja", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 519, LocalGovernmentName = "Ikorodu", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 520, LocalGovernmentName = "Kosofe", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 521, LocalGovernmentName = "Lagos Island", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 522, LocalGovernmentName = "Lagos Mainland", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 523, LocalGovernmentName = "Mushin", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 524, LocalGovernmentName = "Ojo", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 525, LocalGovernmentName = "Oshodi-Isolo", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 526, LocalGovernmentName = "Shomolu", StateId = 25 },
                    new LocalGovernment {  LocalGovernmentId = 527, LocalGovernmentName = "Surulere", StateId = 25 },


                    //Nassarawa

                    new LocalGovernment {  LocalGovernmentId = 528, LocalGovernmentName = "Akwanga", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 529, LocalGovernmentName = "Awe", StateId = 26},
                    new LocalGovernment {  LocalGovernmentId = 530, LocalGovernmentName = "Doma", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 531, LocalGovernmentName = "Karu", StateId = 26 },
                   new LocalGovernment {  LocalGovernmentId = 532, LocalGovernmentName = "Keana", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 533, LocalGovernmentName = "Keffi", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 534, LocalGovernmentName = "Kokona", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 535, LocalGovernmentName = "Lafia", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 536, LocalGovernmentName = "Nasarawa", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 537, LocalGovernmentName = "Nasarawa Egon", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 538, LocalGovernmentName = "Obi", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 539, LocalGovernmentName = "Toto", StateId = 26 },
                    new LocalGovernment {  LocalGovernmentId = 540, LocalGovernmentName = "Wamba", StateId = 26 },


                    //Niger

                    new LocalGovernment {  LocalGovernmentId = 541, LocalGovernmentName = "Agaie", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 542, LocalGovernmentName = "Agwara", StateId = 27},
                    new LocalGovernment {  LocalGovernmentId = 543, LocalGovernmentName = "Bida", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 544, LocalGovernmentName = "Borgu", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 545, LocalGovernmentName = "Bosso", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 546, LocalGovernmentName = "Chanchaga", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 547, LocalGovernmentName = "Edati", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 548, LocalGovernmentName = "Gbako", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 549, LocalGovernmentName = "Gurara", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 550, LocalGovernmentName = "Katcha", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 551, LocalGovernmentName = "Kontagora", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 552, LocalGovernmentName = "Lapai", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 553, LocalGovernmentName = "Lavun", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 554, LocalGovernmentName = "Magama", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 555, LocalGovernmentName = "Mariga", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 556, LocalGovernmentName = "Mashegu", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 557, LocalGovernmentName = "Mokwa", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 558, LocalGovernmentName = "Moya", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 559, LocalGovernmentName = "Paikoro", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 560, LocalGovernmentName = "Rafi", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 561, LocalGovernmentName = "Rijau", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 562, LocalGovernmentName = "Shiroro", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 563, LocalGovernmentName = "Suleja", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 564, LocalGovernmentName = "Tafa", StateId = 27 },
                    new LocalGovernment {  LocalGovernmentId = 565, LocalGovernmentName = "Wushishi", StateId = 27 },
                    

                    //Ogun

                    new LocalGovernment {  LocalGovernmentId = 566, LocalGovernmentName = "Abeokuta North", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 567, LocalGovernmentName = "Abeokuta South", StateId = 28},
                    new LocalGovernment {  LocalGovernmentId = 568, LocalGovernmentName = "Ado-Odo Ota", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 569, LocalGovernmentName = "Egbado North", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 570, LocalGovernmentName = "Egbado South", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 571, LocalGovernmentName = "Ewekoro", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 572, LocalGovernmentName = "Ifo", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 573, LocalGovernmentName = "Ijebu East", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 574, LocalGovernmentName = "Ijebu North", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 575, LocalGovernmentName = "Ijebu North-East", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 576, LocalGovernmentName = "Ijebu Ode", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 577, LocalGovernmentName = "Ikenne", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 578, LocalGovernmentName = "Imeko Afon", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 579,LocalGovernmentName = "Ipokia", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 580, LocalGovernmentName = "Obafemi Owode", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 581, LocalGovernmentName = "Odeda", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 582,LocalGovernmentName = "Odogbolu", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 583, LocalGovernmentName = "Ogun Waterside", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 584, LocalGovernmentName = "Remo North", StateId = 28 },
                    new LocalGovernment {  LocalGovernmentId = 585, LocalGovernmentName = "Shagamu", StateId = 28 },


                    //Ondo
                    new LocalGovernment {  LocalGovernmentId = 586, LocalGovernmentName = "Akoko North-East", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 587, LocalGovernmentName = "Akoko North-West", StateId = 29},
                    new LocalGovernment {  LocalGovernmentId = 588, LocalGovernmentName = "Akoko South-West", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 589, LocalGovernmentName = "Akoko South-East", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 590, LocalGovernmentName = "Akure North", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 591, LocalGovernmentName = "Akure South", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 592, LocalGovernmentName = "Ese Odo", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 593, LocalGovernmentName = "Idanre", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 594, LocalGovernmentName = "Ifedore", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 595, LocalGovernmentName = "Ilaje", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 596, LocalGovernmentName = "Ile Oluji-Okeigbo", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 597, LocalGovernmentName = "Irele", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 598, LocalGovernmentName = "Odigbo", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 599, LocalGovernmentName = "Okitipupa", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 600, LocalGovernmentName = "Ondo East", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 601, LocalGovernmentName = "Ondo West", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 602,LocalGovernmentName = "Ose", StateId = 29 },
                    new LocalGovernment {  LocalGovernmentId = 603, LocalGovernmentName = "Owo", StateId = 29 },
                


                    //Osun


                    new LocalGovernment {  LocalGovernmentId = 604, LocalGovernmentName = "Atakunmosa East", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 605, LocalGovernmentName = "Atakunmosa West", StateId = 30},
                    new LocalGovernment {  LocalGovernmentId = 606, LocalGovernmentName = "Aiyedaade", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 607, LocalGovernmentName = "Aiyedire", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 608, LocalGovernmentName = "Boluwaduro", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 609, LocalGovernmentName = "Boripe", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 610, LocalGovernmentName = "Ede North", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 611, LocalGovernmentName = "Ede South", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 612, LocalGovernmentName = "Ife Central", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 613, LocalGovernmentName = "Ife East", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 614, LocalGovernmentName = "Ife North", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 615, LocalGovernmentName = "Ife South", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 616, LocalGovernmentName = "Egbedore", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 617, LocalGovernmentName = "Ejigbo", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 618, LocalGovernmentName = "Ifedayo", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 619, LocalGovernmentName = "Ifelodun", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 620,LocalGovernmentName = "Ila", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 621, LocalGovernmentName = "Ilesa East", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 622, LocalGovernmentName = "Ilesa West", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 623, LocalGovernmentName = "Irepodun", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 624, LocalGovernmentName = "Irewole", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 625, LocalGovernmentName = "Isokan", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 626, LocalGovernmentName = "Iwo", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 627, LocalGovernmentName = "Obokun", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 628, LocalGovernmentName = "Odo Otin", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 629, LocalGovernmentName = "Ola Oluwa", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 630, LocalGovernmentName = "Olorunda", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 631, LocalGovernmentName = "Oriade", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 632, LocalGovernmentName = "Orolu", StateId = 30 },
                    new LocalGovernment {  LocalGovernmentId = 633, LocalGovernmentName = "Osogbo", StateId = 30 },


                    //oyo
                      new LocalGovernment {  LocalGovernmentId =634, LocalGovernmentName = "Afijio", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 635, LocalGovernmentName = "Akinyele", StateId = 31},
                    new LocalGovernment {  LocalGovernmentId = 636, LocalGovernmentName = "Atiba", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 637, LocalGovernmentName = "Atisbo", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 638, LocalGovernmentName = "Egbeda", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 639, LocalGovernmentName = "Ibadan North", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 640, LocalGovernmentName = "Ibadan North-East", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 641, LocalGovernmentName = "Ibadan North-West", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 642, LocalGovernmentName = "Ibadan South-East", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 643, LocalGovernmentName = "Ibadan South-West", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 644, LocalGovernmentName = "Ibarapa Central", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 645, LocalGovernmentName = "Ibarapa East", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 646, LocalGovernmentName = "Ibarapa North", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 647, LocalGovernmentName = "Ido", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 648, LocalGovernmentName = "Irepo", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 649, LocalGovernmentName = "Iseyin", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 650,LocalGovernmentName = "Itesiwaju", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 651, LocalGovernmentName = "Iwajowa", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 652, LocalGovernmentName = "Kajola", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 653, LocalGovernmentName = "Lagelu", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 654, LocalGovernmentName = "Ogbomosho North", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 655, LocalGovernmentName = "Ogbomosho South", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 656, LocalGovernmentName = "Olorunsogo", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 657, LocalGovernmentName = "Oluyole", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 658, LocalGovernmentName = "Ona Ara", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 659, LocalGovernmentName = "Orelope", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 660, LocalGovernmentName = "Ori Ire", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 661, LocalGovernmentName = "Oyo", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 662, LocalGovernmentName = "Oyo East", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 663, LocalGovernmentName = "Saki East", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 664, LocalGovernmentName = "Saki West", StateId = 31 },
                    new LocalGovernment {  LocalGovernmentId = 665, LocalGovernmentName = "Surulere", StateId = 31 },
                

            //Plateau
                     new LocalGovernment {  LocalGovernmentId = 666, LocalGovernmentName = "Bokkos", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 667, LocalGovernmentName = "Barkin Ladi", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 668, LocalGovernmentName = "Bassa", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 669, LocalGovernmentName = "Jos East", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 670, LocalGovernmentName = "Jos South", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 671, LocalGovernmentName = "Jos North", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 672,LocalGovernmentName = "Kanam", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 673, LocalGovernmentName = "Kanke", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 674, LocalGovernmentName = "Langtang South", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 675, LocalGovernmentName = "Langtang North", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 676, LocalGovernmentName = "Mangu", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 677, LocalGovernmentName = "Mikang", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 678, LocalGovernmentName = "Pankshin", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 679, LocalGovernmentName = "Qua an Pan", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 680, LocalGovernmentName = "Riyom", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 681, LocalGovernmentName = "Shendam", StateId = 32 },
                    new LocalGovernment {  LocalGovernmentId = 682, LocalGovernmentName = "Wase", StateId = 32 },
                


                    //Rivers
                     new LocalGovernment {  LocalGovernmentId = 683, LocalGovernmentName = "Port Harcourt", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 684, LocalGovernmentName = "Obio-Akpor", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 685, LocalGovernmentName = "Okrika", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 686, LocalGovernmentName = "Ogu–Bolo", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 687, LocalGovernmentName = "Eleme", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 688, LocalGovernmentName = "Tai", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 689,LocalGovernmentName = "Gokana", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 690, LocalGovernmentName = "Khana", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 691, LocalGovernmentName = "Oyigbo", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 692, LocalGovernmentName = "Opobo–Nkoro", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 693, LocalGovernmentName = "Andoni", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 694, LocalGovernmentName = "Bonny", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 695, LocalGovernmentName = "Degema", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 696, LocalGovernmentName = "Asari-Toru", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 697, LocalGovernmentName = "Abua–Odual", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 698, LocalGovernmentName = "Ahoada West", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 699, LocalGovernmentName = "Ahoada East", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 700, LocalGovernmentName = "Ogba–Egbema–Ndoni", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 701, LocalGovernmentName = "Emohua", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 702, LocalGovernmentName = "Ikwerre", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 703, LocalGovernmentName = "Etche", StateId = 33 },
                    new LocalGovernment {  LocalGovernmentId = 704, LocalGovernmentName = "Omuma", StateId = 33 },



                    //Sokoto
                    new LocalGovernment {  LocalGovernmentId = 705, LocalGovernmentName = "Binji", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 706, LocalGovernmentName = "Bodinga", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 707, LocalGovernmentName = "Dange Shuni", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 708, LocalGovernmentName = "Gada", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 709, LocalGovernmentName = "Goronyo", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 710, LocalGovernmentName = "Gudu", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 711,LocalGovernmentName = "Gwadabawa", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 712, LocalGovernmentName = "Illela", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 713, LocalGovernmentName = "Isa", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 714, LocalGovernmentName = "Kebbe", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 715, LocalGovernmentName = "Kware", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 716, LocalGovernmentName = "Rabah", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 717, LocalGovernmentName = "Sabon Birni", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 718, LocalGovernmentName = "Shagari", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 719, LocalGovernmentName = "Silame", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 720, LocalGovernmentName = "Sokoto North", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 721, LocalGovernmentName = "Sokoto South", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 722, LocalGovernmentName = "Tambuwal", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 723, LocalGovernmentName = "Tangaza", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 724, LocalGovernmentName = "Tureta", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 725, LocalGovernmentName = "Wamako", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 726, LocalGovernmentName = "Wurno", StateId = 34 },
                    new LocalGovernment {  LocalGovernmentId = 727, LocalGovernmentName = "Yabo", StateId = 34 },



                    //Taraba
                    new LocalGovernment {  LocalGovernmentId = 728, LocalGovernmentName = "Ardo Kola", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 729, LocalGovernmentName = "Bali", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 730, LocalGovernmentName = "Donga", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 731, LocalGovernmentName = "Gashaka", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 732, LocalGovernmentName = "Gassol", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 733, LocalGovernmentName = "Ibi", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 734,LocalGovernmentName = "Jalingo", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 735, LocalGovernmentName = "Karim Lamido", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 736, LocalGovernmentName = "Kumi", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 737, LocalGovernmentName = "Lau", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 738, LocalGovernmentName = "Takum", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 739, LocalGovernmentName = "Ussa", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 740, LocalGovernmentName = "Wukari", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 741, LocalGovernmentName = "Yorro", StateId = 35 },
                    new LocalGovernment {  LocalGovernmentId = 742, LocalGovernmentName = "Zing", StateId = 35 },
                    



                    //Yobe
                    new LocalGovernment {  LocalGovernmentId = 743, LocalGovernmentName = "Bade", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 744, LocalGovernmentName = "Bursari", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 745, LocalGovernmentName = "Damaturu", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 746, LocalGovernmentName = "Fika", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 747, LocalGovernmentName = "Fune", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 748, LocalGovernmentName = "Geidam", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 749,LocalGovernmentName = "Gujba", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 750, LocalGovernmentName = "Gulani", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 751, LocalGovernmentName = "Jakusko", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 752, LocalGovernmentName = "Karasuwa", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 753, LocalGovernmentName = "Machina", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 754, LocalGovernmentName = "Nangere", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 755, LocalGovernmentName = "Wukari", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 756, LocalGovernmentName = "Nguru", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 757, LocalGovernmentName = "Potiskum", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 758, LocalGovernmentName = "Tarmuwa", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 759, LocalGovernmentName = "Yunusari", StateId = 36 },
                    new LocalGovernment {  LocalGovernmentId = 760, LocalGovernmentName = "Yusufari", StateId = 36 },


                    //Zamfara
                    new LocalGovernment {  LocalGovernmentId = 761, LocalGovernmentName = "Anka", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 762, LocalGovernmentName = "Bakura", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 763, LocalGovernmentName = "Birnin Magaji Kiyaw',", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 764, LocalGovernmentName = "Bukkuyum", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 765, LocalGovernmentName = "Bungudu", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 766, LocalGovernmentName = "Gummi", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 767,LocalGovernmentName = "Gusau", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 768, LocalGovernmentName = "Kaura Namoda',", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 769, LocalGovernmentName = "Maradun", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 770, LocalGovernmentName = "Maru", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 771, LocalGovernmentName = "Shinkafi", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 772, LocalGovernmentName = "Talata Mafara", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 773, LocalGovernmentName = "Chafe", StateId = 37 },
                    new LocalGovernment {  LocalGovernmentId = 774, LocalGovernmentName = "Zurmi", StateId = 37 },

                }
             );
        }
    }
}
